--------------------------------------------------
-- 회원

DROP TABLE "MEMBER";
CREATE TABLE "MEMBER" (
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(60)		NOT NULL,
	"MEMBER_NICK"	VARCHAR2(24)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(255)		NOT NULL,
	"MEMBER_TEL"	VARCHAR2(20)		NOT NULL,
	"PROFILE_IMG"	VARCHAR2(255)		NULL,
	"ENROLL_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PROMOTION_FL"	CHAR(1)	DEFAULT 'N'	NULL,
	"DELETED_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICK" IS '회원 닉네임';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';
COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '가입일';
COMMENT ON COLUMN "MEMBER"."PROMOTION_FL" IS '마케팅 수신 동의 여부';
COMMENT ON COLUMN "MEMBER"."DELETED_FL" IS '탈퇴 여부';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_ID"
);

COMMENT ON COLUMN "COMPANY"."CMPN_NO" IS '회사 번호';
COMMENT ON COLUMN "BOARD_RECRUIT"."CMPN_NO" IS '회사 번호';
--------------------------------------------------
-- 이력서

DROP TABLE "RESUME";
CREATE TABLE "RESUME" (
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"POSITION"	VARCHAR2(60)		NULL,
	"EXPR_PERIOD"	VARCHAR2(120)		NULL,
	"EMPL_TYPE"	VARCHAR2(60)		NULL,
	"EMPL_LOCATION"	VARCHAR2(255)		NULL,
	"SALARY_EXPECT"	NUMBER		NULL
);

COMMENT ON COLUMN "RESUME"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "RESUME"."POSITION" IS '분야';
COMMENT ON COLUMN "RESUME"."EXPR_PERIOD" IS '경력 기간';
COMMENT ON COLUMN "RESUME"."EMPL_TYPE" IS '업무 형태';
COMMENT ON COLUMN "RESUME"."EMPL_LOCATION" IS '근무 지역';
COMMENT ON COLUMN "RESUME"."SALARY_EXPECT" IS '희망 급여';

ALTER TABLE "RESUME" ADD CONSTRAINT "PK_RESUME" PRIMARY KEY (
	"MEMBER_ID"
);

--------------------------------------------------
-- 회원 자격

DROP TABLE "AUTHORITY";
CREATE TABLE "AUTHORITY" (
	"AUTHORITY"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "AUTHORITY"."AUTHORITY" IS '회원 자격';
COMMENT ON COLUMN "AUTHORITY"."MEMBER_ID" IS '회원 아이디';

ALTER TABLE "AUTHORITY" ADD CONSTRAINT "PK_AUTHORITY" PRIMARY KEY (
	"AUTHORITY",
	"MEMBER_ID"
);

--------------------------------------------------
-- 팔로우

DROP TABLE "FOLLOW";
CREATE TABLE "FOLLOW" (
	"FOLLOW_FROM"	VARCHAR2(20)		NOT NULL,
	"FOLLOW_TO"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "FOLLOW"."FOLLOW_FROM" IS '주체 아이디';
COMMENT ON COLUMN "FOLLOW"."FOLLOW_TO" IS '대상 아이디';

ALTER TABLE "FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY (
	"FOLLOW_FROM"
);

--------------------------------------------------
-- 회사

DROP TABLE "COMPANY";
CREATE TABLE "COMPANY" (
	"CMPN_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"CMPN_NM"	VARCHAR2(60)		NOT NULL,
	"CMPN_ADDR"	VARCHAR2(255)		NULL,
	"CMPN_LOGO"	VARCHAR2(255)		NULL,
	"CMPN_INTRO"	VARCHAR2(4000)		NULL,
	"CMPN_MCOUNT"	NUMBER		NULL,
	"CMPN_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "COMPANY"."CMPN_NO" IS '회사 아이디';

COMMENT ON COLUMN "COMPANY"."MEMBER_ID" IS '담당자 아이디';

COMMENT ON COLUMN "COMPANY"."CMPN_NM" IS '회사 이름';

COMMENT ON COLUMN "COMPANY"."CMPN_ADDR" IS '회사 주소';

COMMENT ON COLUMN "COMPANY"."CMPN_LOGO" IS '회사 로고';

COMMENT ON COLUMN "COMPANY"."CMPN_INTRO" IS '회사 소개';

COMMENT ON COLUMN "COMPANY"."CMPN_MCOUNT" IS '사원 수';

COMMENT ON COLUMN "COMPANY"."CMPN_FL" IS '승인 여부';

ALTER TABLE "COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY (
	"CMPN_NO"
);

DROP SEQUENCE "SEQ_CMPN_NO";
CREATE SEQUENCE SEQ_CMPN_NO NOCACHE;

--------------------------------------------------

--------------------------------------------------
-- 댓글

DROP TABLE "COMMENT";
CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(600)		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DT"	DATE		NULL,
	"PARENT_NO"	NUMBER		NULL,
	"DELETED_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호';
COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호';
COMMENT ON COLUMN "COMMENT"."MEMBER_ID" IS '작성자 아이디';
COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';
COMMENT ON COLUMN "COMMENT"."CREATE_DT" IS '댓글 작성일';
COMMENT ON COLUMN "COMMENT"."MODIFY_DT" IS '댓글 수정일';
COMMENT ON COLUMN "COMMENT"."PARENT_NO" IS '부모 댓글 번호';
COMMENT ON COLUMN "COMMENT"."DELETED_FL" IS '댓글 삭제 여부';

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
    
);

ALTER TABLE "BOARD_STUDY" ADD STUDY_STATUS CHAR(1) DEFAULT 'N' NOT NULL;


DROP SEQUENCE "SEQ_COMMENT_NO";
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;

INSERT INTO "COMMENT" VALUES(1, 500, 'user01', '테스트' , SYSDATE, NULL, NULL, DEFAULT);
COMMIT;
--------------------------------------------------
-- 좋아요

DROP TABLE "LIKE";
CREATE TABLE "LIKE" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "LIKE"."BOARD_NO" IS '게시글 번호';
COMMENT ON COLUMN "LIKE"."MEMBER_ID" IS '회원 아이디';

ALTER TABLE "LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"BOARD_NO",
	"MEMBER_ID"
);

--------------------------------------------------
-- 북마크

DROP TABLE "BOOKMARK";
CREATE TABLE "BOOKMARK" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOOKMARK"."BOARD_NO" IS '게시글 번호';
COMMENT ON COLUMN "BOOKMARK"."MEMBER_ID" IS '회원 아이디';

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "PK_BOOKMARK" PRIMARY KEY (
	"BOARD_NO",
	"MEMBER_ID"
);

--------------------------------------------------
-- 스터디

DROP TABLE "STUDY";
CREATE TABLE "STUDY" (
	"STUDY_NO"	NUMBER		NOT NULL,
	"STUDY_TITLE"	VARCHAR2(60)		NULL,
	"LEADER_ID"	VARCHAR2(20)		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "STUDY"."STUDY_NO" IS '스터디 번호';
COMMENT ON COLUMN "STUDY"."STUDY_TITLE" IS '스터디 이름';
COMMENT ON COLUMN "STUDY"."LEADER_ID" IS '회원 아이디';
COMMENT ON COLUMN "STUDY"."CREATE_DT" IS '스터디 생성 일시';

ALTER TABLE "STUDY" ADD CONSTRAINT "PK_STUDY" PRIMARY KEY (
	"STUDY_NO"
);

DROP SEQUENCE "SEQ_STUDY_NO";
CREATE SEQUENCE SEQ_STUDY_NO NOCACHE;

--------------------------------------------------
-- 스터디 회원

DROP TABLE "STUDY_MEMBER";
CREATE TABLE "STUDY_MEMBER" (
	"STUDY_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "STUDY_MEMBER"."STUDY_NO" IS '스터디 번호';
COMMENT ON COLUMN "STUDY_MEMBER"."MEMBER_ID" IS '회원 아이디';

ALTER TABLE "STUDY_MEMBER" ADD CONSTRAINT "PK_STUDY_MEMBER" PRIMARY KEY (
	"STUDY_NO",
	"MEMBER_ID"
);

--------------------------------------------------

--------------------------------------------------
-- 채용 공고 게시글

DROP TABLE "BOARD_RECRUIT";
CREATE TABLE "BOARD_RECRUIT" (                <textarea name="employmentBenefits" placeholder=" 복리후생을 작성해주세요. ( 🛀 ex : 1년 이상 재직자에 한해 50만원 상당의 건강검진 패키지를 제공합니다.)"  class="qualRespTextArea" id="qualrespTextArea4" maxlength="900"></textarea>
	"BOARD_NO"	NUMBER		NOT NULL,
	"CMPN_NO"	NUMBER		NOT NULL,
	"POSITION"	VARCHAR2(60)		NULL,
	"EXPR_PERIOD"	VARCHAR2(120)		NULL,
	"EMPL_TYPE"	VARCHAR2(60)		NULL,
	"EMPL_CNDT"	VARCHAR2(900)		NULL,
	"ENTR_EXAM"	VARCHAR2(900)		NULL,
	"JOB_TYPE"	VARCHAR2(60)		NULL,
	"BENEFIT"	VARCHAR2(900)		NULL
);

COMMENT ON COLUMN "BOARD_RECRUIT"."BOARD_NO" IS '게시글 번호';
COMMENT ON COLUMN "BOARD_RECRUIT"."CMPN_NO" IS '회사 아이디';
COMMENT ON COLUMN "BOARD_RECRUIT"."POSITION" IS '모집 분야';
COMMENT ON COLUMN "BOARD_RECRUIT"."EXPR_PERIOD" IS '경력 기간';
COMMENT ON COLUMN "BOARD_RECRUIT"."EMPL_TYPE" IS '근무 형태';
COMMENT ON COLUMN "BOARD_RECRUIT"."EMPL_CNDT" IS '근무 조건';
COMMENT ON COLUMN "BOARD_RECRUIT"."ENTR_EXAM" IS '전형 절차';
COMMENT ON COLUMN "BOARD_RECRUIT"."JOB_TYPE" IS '고용 형태';
COMMENT ON COLUMN "BOARD_RECRUIT"."BENEFIT" IS '복리후생';

ALTER TABLE "BOARD_RECRUIT" ADD CONSTRAINT "PK_BOARD_RECRUIT" PRIMARY KEY (
	"BOARD_NO"
);

--------------------------------------------------
-- 스터디 모집글

DROP TABLE "BOARD_STUDY";
CREATE TABLE "BOARD_STUDY" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"STUDY_NO"	NUMBER		NOT NULL,
	"LOCATION"	VARCHAR2(100)		NULL,
	"HEAD_COUNT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_STUDY"."BOARD_NO" IS '게시글 번호';
COMMENT ON COLUMN "BOARD_STUDY"."STUDY_NO" IS '스터디 번호';
COMMENT ON COLUMN "BOARD_STUDY"."LOCATION" IS '스터디 위치';
COMMENT ON COLUMN "BOARD_STUDY"."HEAD_COUNT" IS '인원수';

ALTER TABLE "BOARD_STUDY" ADD CONSTRAINT "PK_BOARD_STUDY" PRIMARY KEY (
	"BOARD_NO"
);

--------------------------------------------------
-- 채팅방

DROP TABLE "CHAT_ROOM";
CREATE TABLE "CHAT_ROOM" (
	"CROOM_NO"	NUMBER		NOT NULL,
	"CREATE_DT"	DATE		NOT NULL,
	"CROOM_TYPE"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "CHAT_ROOM"."CROOM_NO" IS '채팅방 번호';
COMMENT ON COLUMN "CHAT_ROOM"."CREATE_DT" IS '생성일시';
COMMENT ON COLUMN "CHAT_ROOM"."CROOM_TYPE" IS '채팅방 유형';

ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "PK_CHAT_ROOM" PRIMARY KEY (
	"CROOM_NO"
);

DROP SEQUENCE "SEQ_CROOM_NO";
CREATE SEQUENCE SEQ_CROOM_NO NOCACHE;

--------------------------------------------------
-- 메시지

DROP TABLE "MESSAGE";
CREATE TABLE "MESSAGE" (
	"MSG_NO"	NUMBER		NOT NULL,
	"CROOM_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MSG_CONTENT"	VARCHAR2(600)		NOT NULL,
	"SEND_DT"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "MESSAGE"."MSG_NO" IS '메시지 번호';
COMMENT ON COLUMN "MESSAGE"."CROOM_NO" IS '채팅방 번호';
COMMENT ON COLUMN "MESSAGE"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MESSAGE"."MSG_CONTENT" IS '메시지';
COMMENT ON COLUMN "MESSAGE"."SEND_DT" IS '전송일시';

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MSG_NO"
);

DROP SEQUENCE "SEQ_MSG_NO";
CREATE SEQUENCE SEQ_MSG_NO NOCACHE;

--------------------------------------------------
-- 채팅 세션

DROP TABLE "CHAT_SESSION";
CREATE TABLE "CHAT_SESSION" (
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"CROOM_NO"	NUMBER		NOT NULL,
	"SEEN_DT"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "CHAT_SESSION"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "CHAT_SESSION"."CROOM_NO" IS '채팅방 번호';
COMMENT ON COLUMN "CHAT_SESSION"."SEEN_DT" IS '읽음 일시';

ALTER TABLE "CHAT_SESSION" ADD CONSTRAINT "PK_CHAT_SESSION" PRIMARY KEY (
	"MEMBER_ID",
	"CROOM_NO"
);

--------------------------------------------------
-- 태그

DROP TABLE "TAG";
CREATE TABLE "TAG" (
	"TAG_NO"	NUMBER		NOT NULL,
	"TAG_NM"	VARCHAR(30)		NOT NULL
);

COMMENT ON COLUMN "TAG"."TAG_NO" IS '태그 번호';
COMMENT ON COLUMN "TAG"."TAG_NM" IS '태그 이름';

ALTER TABLE "TAG" ADD CONSTRAINT "PK_TAG" PRIMARY KEY (
	"TAG_NO"
);

DROP SEQUENCE "TAG_NO";
DROP SEQUENCE "SEQ_TAG_NO";
CREATE SEQUENCE SEQ_TAG_NO NOCACHE;

--------------------------------------------------
-- 태그 관계

DROP TABLE "TAG_RELATION";
CREATE TABLE "TAG_RELATION" (
	"TAG_NO"	NUMBER		NOT NULL,
	"ITEM_TYPE"	NUMBER		NOT NULL,
	"ITEM_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "TAG_RELATION"."TAG_NO" IS '태그 번호';
COMMENT ON COLUMN "TAG_RELATION"."ITEM_TYPE" IS '아이템 유형';
COMMENT ON COLUMN "TAG_RELATION"."ITEM_NO" IS '아이템 번호';

ALTER TABLE "TAG" ADD CONSTRAINT "PK_TAG" PRIMARY KEY (
	"TAG_NO",
	"ITEM_TYPE",
	"ITEM_NO"
);

--------------------------------------------------
-- 태그 종속

DROP TABLE "TAG_DEPENDENCY";
CREATE TABLE "TAG_DEPENDENCY" (
	"SUPER_TAG_NO"	NUMBER		NOT NULL,
	"SUB_TAG_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "TAG_DEPENDENCY"."SUPER_TAG_NO" IS '슈퍼 태그 번호';
COMMENT ON COLUMN "TAG_DEPENDENCY"."SUB_TAG_NO" IS '서브 태그 번호';

ALTER TABLE "TAG_DEPENDENCY" ADD CONSTRAINT "PK_TAG_DEPENDENCY" PRIMARY KEY (
	"SUPER_TAG_NO",
	"SUB_TAG_NO"
);

COMMIT;


DROP TABLE "TAG_RELATION";
CREATE TABLE "TAG_RELATION" (
	"TAG_NO"	NUMBER		NOT NULL,
	"ITEM_TYPE"	NUMBER		NOT NULL,
	"ITEM_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "TAG_RELATION"."TAG_NO" IS '태그 번호';
COMMENT ON COLUMN "TAG_RELATION"."ITEM_TYPE" IS '아이템 유형';
COMMENT ON COLUMN "TAG_RELATION"."ITEM_NO" IS '아이템 번호';

ALTER TABLE "TAG_RELATION" ADD CONSTRAINT "PK_TAG_RELATION" PRIMARY KEY (
	"TAG_NO",
	"ITEM_TYPE",
	"ITEM_NO"
);

DROP TABLE BOARD;

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(60)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)	NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DT"	DATE		NULL,
	"DELETED_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD"."MEMBER_ID" IS '게시글 작성자';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."MODIFY_DT" IS '게시글 수정일';

COMMENT ON COLUMN "BOARD"."DELETED_FL" IS '게시글 삭제여부';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

----------- 회원 더미
INSERT INTO MEMBER
VALUES('user01', 'pass01', '유저일', 'user01@kh.or.kr', '01012341234', null,
    default, default, default);
    
INSERT INTO MEMBER
VALUES('user02', '2', '유저이', 'user01@kh.or.kr', '01012341234', null,
    default, default, default);
    
    COMMIT;

            INSERT INTO TAG (TAG_NO, TAG_NM) VALUES (1, '프론트엔드');
            INSERT INTO TAG (TAG_NO, TAG_NM) VALUES (2, '백엔드');
            INSERT INTO TAG (TAG_NO, TAG_NM) VALUES (3, '디자인');
            INSERT INTO TAG (TAG_NO, TAG_NM) VALUES (4, '기획');
            INSERT INTO TAG (TAG_NO, TAG_NM) VALUES (5, '기타');
            COMMIT;
            
            
            
        SELECT B.BOARD_NO, B.MEMBER_ID, B.BOARD_TITLE, B.BOARD_CONTENT, B.CREATE_DT, B.MODIFY_DT, B.DELETED_FL, B.READ_COUNT, BG.BOARD_CODE, M.MEMBER_NICK
			  ,(SELECT COUNT(*) FROM "COMMENT" C WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT
			  ,(SELECT LISTAGG(T.TAG_NM, ', ') WITHIN GROUP (ORDER BY T.TAG_NM) 
			  FROM TAG_RELATION TR
			  JOIN TAG T ON TR.TAG_NO = T.TAG_NO
			  WHERE TR.ITEM_NO = B.BOARD_NO) TAGS
		FROM BOARD B
		JOIN BOARD_GENERAL BG ON (B.BOARD_NO = BG.BOARD_NO)
		JOIN MEMBER M ON (B.MEMBER_ID = M.MEMBER_ID)
		WHERE BG.BOARD_CODE = 1
		AND B.DELETED_FL = 'N'
		AND (B.BOARD_TITLE LIKE '%' || 'ㅂㅇ' || '%' OR B.BOARD_CONTENT LIKE '%' || 'ㅎㅇ' || '%')
		ORDER BY BOARD_NO DESC;
        
        
        SELECT B.BOARD_NO, B.BOARD_TITLE, B.CREATE_DT, B.READ_COUNT 
        FROM BOARD B
        JOIN BOOKMARK BM ON BM.BOARD_NO = B.BOARD_NO
        WHERE BM.MEMBER_ID = 'user01';
        
        
		INSERT ALL
		
		INTO BOARD (BOARD_NO, MEMBER_ID, BOARD_TITLE, BOARD_CONTENT, CREATE_DT, DELETED_FL, READ_COUNT)
            VALUES (1500, 'user01', '테스트', '테스트내용', DEFAULT, DEFAULT, '{boardCode}')
			
		INTO BOARD_GENERAL (BOARD_NO, BOARD_CODE) VALUES(#{boardNo}, #{boardCode})
        
        SELECT BOARD_NO, CMPN_NO,;
        
        
        DROP TABLE "RESUME";
        
    CREATE TABLE "RESUME" (
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"POSITION"	VARCHAR2(60)		NULL,
	"EXPR_PERIOD"	VARCHAR2(120)		NULL,
	"EMPL_TYPE"	VARCHAR2(60)		NULL,
	"EMPL_LOCATION"	VARCHAR2(255)		NULL,
	"SALARY_EXPECT"	NUMBER		NULL,
	"FIELD"	VARCHAR2(300)		NULL
);

ALTER TABLE "RESUME" ADD CONSTRAINT "PK_RESUME" PRIMARY KEY (
   "MEMBER_ID"
);

COMMENT ON COLUMN "RESUME"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "RESUME"."POSITION" IS '분야';

COMMENT ON COLUMN "RESUME"."EXPR_PERIOD" IS '경력 기간';

COMMENT ON COLUMN "RESUME"."EMPL_TYPE" IS '업무 형태';

COMMENT ON COLUMN "RESUME"."EMPL_LOCATION" IS '근무 지역';

COMMENT ON COLUMN "RESUME"."SALARY_EXPECT" IS '희망 급여';

COMMENT ON COLUMN "RESUME"."FIELD" IS '가능한 기술';

CREATE TABLE "LECTURE" (
	"LCTR_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"LCTR_TITLE"	VARCHAR2(90)		NOT NULL,
	"LCTR_INTRO"	VARCHAR2(4000)		NULL,
	"LCTR_THUMB"	VARCHAR2(255)		NULL,
	"LCTR_DIFF"	CHAR(1)	DEFAULT 1	NOT NULL,
	"LCTR_PRICE"	NUMBER	DEFAULT 0	NOT NULL,
	"LCTR_SALE"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "LECTURE"."LCTR_NO" IS '강의 번호';

COMMENT ON COLUMN "LECTURE"."MEMBER_ID" IS '강사 아이디';

COMMENT ON COLUMN "LECTURE"."LCTR_TITLE" IS '강의 이름';

COMMENT ON COLUMN "LECTURE"."LCTR_INTRO" IS '강의 소개';

COMMENT ON COLUMN "LECTURE"."LCTR_THUMB" IS '강의 썸네일';

COMMENT ON COLUMN "LECTURE"."LCTR_DIFF" IS '강의 난이도';

COMMENT ON COLUMN "LECTURE"."LCTR_PRICE" IS '강의 가격';

COMMENT ON COLUMN "LECTURE"."LCTR_SALE" IS '강의 할인율';

INSERT INTO BOARD_RECRUIT (BOARD_NO, CMPN_NO) BR (SEQ_BOARD_NO.NEXTVAL,  
JOIN BOARD B
JOIN COMPANY CP
BOARD
BOARD_RECRUIT

TAG;

SELECT * FROM COMPANY WHERE MEMBER_ID = 'user01';

ALTER TABLE COMPANY
ADD CMPN_FL NOT NULL DEFAULT 'N'; 

ALTER TABLE COMPANY
ADD CMPN_HP VARCHAR2(2000) NULL;

INSERT INTO BOARD 

