-- 게시판
DROP TABLE BOARD_TYPE;
DROP TABLE BOARD_GENERAL;
DROP TABLE BOARD;
DROP SEQUENCE SEQ_BOARD_NO;

ALTER TABLE COMPANY
ADD CMPN_FL VARCHAR(1) DEFAULT 'N';


ALTER TABLE BOARD_RECRUIT
ADD SALARYINFO VARCHAR2(100) DEFAULT '비공개';
CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(60)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DT"	DATE		NULL,
	"DELETED_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD"."MEMBER_ID" IS '게시글 작성자';


COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."MODIFY_DT" IS '게시글 수정일';

COMMENT ON COLUMN "BOARD"."DELETED_FL" IS '게시글 삭제여부';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY ("BOARD_NO");

CREATE SEQUENCE SEQ_BOARD_NO;

-- 일반 게시판
CREATE TABLE "BOARD_GENERAL" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_CODE"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "BOARD_GENERAL"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD_GENERAL"."BOARD_CODE" IS '일반게시판 게시판번호';

BEGIN
   FOR I IN 1..500 LOOP
      INSERT INTO BOARD (
         BOARD_NO,
         MEMBER_ID,
         BOARD_TITLE,
         BOARD_CONTENT,
         CREATE_DT,
         MODIFY_DT,
         DELETED_FL,
         READ_COUNT
      )
      VALUES (
         SEQ_BOARD_NO.NEXTVAL,
         'user01',
         SEQ_BOARD_NO.CURRVAL || '번째 게시글',
         SEQ_BOARD_NO.CURRVAL || '번째 게시글 내용 입니다.',
         DEFAULT,
         DEFAULT,
         DEFAULT,
         0
      );

      INSERT INTO BOARD_GENERAL (
         BOARD_NO,
         BOARD_CODE
      )
      VALUES (
         SEQ_BOARD_NO.CURRVAL,
         TO_CHAR(CEIL(DBMS_RANDOM.VALUE(0, 3)))
      );
   END LOOP;
   COMMIT;
END;
/

		SELECT LEVEL, C.* FROM
		(SELECT COMMENT_NO, COMMENT_CONTENT,
		       TO_CHAR(CREATE_DT, 'YYYY"년"MM"월"DD"일"HH"시"MM"분"SS"초"') CREATE_DT,
		       BOARD_NO, COM.MEMBER_ID, MEM.MEMBER_NICK, MEM.PROFILE_IMG, COM.PARENT_NO, COM.DELETED_FL
		FROM "COMMENT" COM
		JOIN MEMBER MEM ON (COM.MEMBER_ID = MEM.MEMBER_ID)
		WHERE BOARD_NO = 1) C
		WHERE DELETED_FL = 'N'
		START WITH PARENT_NO IS NULL 
		CONNECT BY PRIOR COMMENT_NO = PARENT_NO 
		ORDER SIBLINGS BY COMMENT_NO;
    

