ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER helloworld IDENTIFIED BY helloworld1234;
GRANT CONNECT, RESOURCE TO helloworld;
ALTER USER helloworld DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

--------------------------------------------------
-- 회원 테이블

CREATE TABLE "MEMBER" (
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(60)		NOT NULL,
	"MEMBER_NICK"	VARCHAR2(24)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(255)		NOT NULL,
	"MEMBER_TEL"	VARCHAR2(20)		NOT NULL,
	"PROFILE_IMG"	VARCHAR2(255)		NULL,
	"ENROLL_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PROMOTION_FL"	CHAR(1)	DEFAULT 'N'	NULL,
	"DELETED_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICK" IS '회원 닉네임';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';
COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '가입일';
COMMENT ON COLUMN "MEMBER"."PROMOTION_FL" IS '마케팅 수신 동의 여부';
COMMENT ON COLUMN "MEMBER"."DELETED_FL" IS '탈퇴 여부';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_ID"
);

--------------------------------------------------
-- 회사 테이블

CREATE TABLE "COMPANY" (
	"CMPN_NO"	NUMBER	    NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)        NOT NULL,
	"CMPN_NM"	VARCHAR2(60)		NOT NULL,
	"CMPN_ADDR"	VARCHAR2(255)		NULL,
	"CMPN_LOGO"	VARCHAR2(255)		NULL,
	"CMPN_INTRO"	VARCHAR2(4000)		NULL,
	"CMPN_MCOUNT"	NUMBER		NULL,
	"CREATE_DT"	DATE		NULL
);

COMMENT ON COLUMN "COMPANY"."CMPN_NO" IS '회사 아이디';
COMMENT ON COLUMN "COMPANY"."MEMBER_ID" IS '담당자 아이디';
COMMENT ON COLUMN "COMPANY"."CMPN_NM" IS '회사 이름';
COMMENT ON COLUMN "COMPANY"."CMPN_ADDR" IS '회사 주소';
COMMENT ON COLUMN "COMPANY"."CMPN_LOGO" IS '회사 로고';
COMMENT ON COLUMN "COMPANY"."CMPN_INTRO" IS '회사 소개';
COMMENT ON COLUMN "COMPANY"."CMPN_MCOUNT" IS '사원 수';
COMMENT ON COLUMN "COMPANY"."CREATE_DT" IS '설립일';

ALTER TABLE "COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY (
	"CMPN_NO"
);

CREATE SEQUENCE SEQ_CMPN_NO NOCACHE;

--------------------------------------------------
-- 스터디 테이블

CREATE TABLE "STUDY" (
	"STUDY_NO"	NUMBER		NOT NULL,
	"STUDY_TITLE"	VARCHAR2(60)		NULL,
	"LEADER_ID"	VARCHAR2(20)		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "STUDY"."STUDY_NO" IS '스터디 번호';
COMMENT ON COLUMN "STUDY"."STUDY_TITLE" IS '스터디 이름';
COMMENT ON COLUMN "STUDY"."LEADER_ID" IS '회원 아이디';
COMMENT ON COLUMN "STUDY"."CREATE_DT" IS '스터디 생성 일시';

ALTER TABLE "STUDY" ADD CONSTRAINT "PK_STUDY" PRIMARY KEY (
	"STUDY_NO"
);

CREATE SEQUENCE SEQ_STUDY_NO NOCACHE;

--------------------------------------------------
-- 스터디 회원 테이블

CREATE TABLE "STUDY_MEMBER" (
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"STUDY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "STUDY_MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "STUDY_MEMBER"."STUDY_NO" IS '스터디 번호';

ALTER TABLE "STUDY_MEMBER" ADD CONSTRAINT "PK_STUDY_MEMBER" PRIMARY KEY (
	"MEMBER_ID",
	"STUDY_NO"
);

--------------------------------------------------
-- 채용 공고 테이블

CREATE TABLE "RECRUIT" (
	"RECR_NO"	NUMBER		NOT NULL,
	"RECR_TITLE"	VARCHAR2(60)		NULL,
	"RECR_CONTENT"	VARCHAR2(4000)		NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"CMPN_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUIT"."RECR_NO" IS '공고 번호';
COMMENT ON COLUMN "RECRUIT"."RECR_TITLE" IS '공고 제목';
COMMENT ON COLUMN "RECRUIT"."RECR_CONTENT" IS '공고 내용';
COMMENT ON COLUMN "RECRUIT"."MEMBER_ID" IS '작성자';
COMMENT ON COLUMN "RECRUIT"."CMPN_NO" IS '회사 아이디';

ALTER TABLE "RECRUIT" ADD CONSTRAINT "PK_RECRUIT" PRIMARY KEY (
	"RECR_NO"
);

CREATE SEQUENCE SEQ_RECR_NO NOCACHE;

--------------------------------------------------
-- 태그 테이블

CREATE TABLE "TAG" (
	"TAG_NO"	NUMBER		NOT NULL,
	"TAG_NM"	VARCHAR(30)		NOT NULL,
	"TAG_TREND_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "TAG"."TAG_NO" IS '태그 번호';
COMMENT ON COLUMN "TAG"."TAG_NM" IS '태그 이름';
COMMENT ON COLUMN "TAG"."TAG_TREND_FL" IS '태그 트렌드 여부';

ALTER TABLE "TAG" ADD CONSTRAINT "PK_TAG" PRIMARY KEY (
	"TAG_NO"
);

CREATE SEQUENCE TAG_NO NOCACHE;

--------------------------------------------------
-- 스터디 태그 테이블

CREATE TABLE "STUDY_TAG" (
	"STUDY_NO"	NUMBER		NOT NULL,
	"TAG_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "STUDY_TAG"."STUDY_NO" IS '스터디 번호';
COMMENT ON COLUMN "STUDY_TAG"."TAG_NO" IS '태그 번호';

ALTER TABLE "STUDY_TAG" ADD CONSTRAINT "PK_STUDY_TAG" PRIMARY KEY (
	"STUDY_NO",
	"TAG_NO"
);

--------------------------------------------------
-- 채용 공고 태그 테이블

CREATE TABLE "RECRUIT_TAG" (
	"RECR_NO"	NUMBER		NOT NULL,
	"TAG_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUIT_TAG"."RECR_NO" IS '공고 번호';
COMMENT ON COLUMN "RECRUIT_TAG"."TAG_NO" IS '태그 번호';

ALTER TABLE "RECRUIT_TAG" ADD CONSTRAINT "PK_RECRUIT_TAG" PRIMARY KEY (
	"RECR_NO",
	"TAG_NO"
);
--------------------------------------------------
-- 게시판

DROP TABLE BOARD;
CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(60)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_CODE"	CHAR(1)		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DT"	DATE		NULL,
	"DELETED_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);


BEGIN
   FOR I IN 1..500 LOOP
      INSERT INTO BOARD 
      VALUES( SEQ_BOARD_NO.NEXTVAL, 1,
              SEQ_BOARD_NO.CURRVAL || '번째 게시글',
              SEQ_BOARD_NO.CURRVAL || '번째 게시글 내용 입니다.',
              CEIL(DBMS_RANDOM.VALUE(0,3)),
              DEFAULT, DEFAULT, DEFAULT
      );
   END LOOP;
END;
/

commit;

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD"."MEMBER_ID" IS '게시글 작성자';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_TYPE" IS '게시글 유형';

COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."MODIFY_DT" IS '게시글 수정일';

COMMENT ON COLUMN "BOARD"."DELETED_FL" IS '게시글 삭제여부';

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;

DROP TABLE BOARD_TYPE;
CREATE TABLE  BOARD_TYPE(
"BOARD_CODE"	CHAR(1)		NOT NULL,
"BOARD_NAME" VARCHAR(25) NOT NULL
);

INSERT INTO BOARD_TYPE VALUES(1, '공지사항');
INSERT INTO BOARD_TYPE VALUES(2, '자유 게시판');
INSERT INTO BOARD_TYPE VALUES(3, 'Q&A 게시판');
COMMIT;

INSERT INTO MEMBER
VALUES('user01', 'pass01', '유저일', 'user01@kh.or.kr', '01012341234', null,
    default, default, default);
    
INSERT INTO MEMBER
VALUES('user02', '2', '유저이', 'user01@kh.or.kr', '01012341234', null,
    default, default, default);

commit;