-- sys 관리자 계정
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER kh IDENTIFIED BY kh;

ALTER USER kh DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CONNECT, RESOURCE, CREATE VIEW TO kh;



CREATE TABLE MEMBER(

MEMBER_ID VARCHAR2(30) PRIMARY KEY,

MEMBER_PWD VARCHAR2(100) NOT NULL,

MEMBER_NM VARCHAR2(15) NOT NULL,

MEMBER_ENROLL_DT DATE DEFAULT SYSDATE

);

INSERT INTO MEMBER VALUES('user01', 'pass01', '홍길동', DEFAULT);
commit;

		SELECT BOARD_TITLE, BOARD_CONTENT, EMPL_CNDT, ENTR_EXAM, BENEFIT, POSITION, JOB_TYPE, CMPN_ADDR, CMPN_NO, CMPN_INTRO, 
			CMPN_NM, CMPN_LOGO
			FROM BOARD
			JOIN BOARD_RECRUIT USING (BOARD_NO)
			JOIN COMPANY USING (CMPN_NO)
		WHERE BOARD_NO = 1500;