-- sys 관리자 계정
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER ncsUser IDENTIFIED BY ncsUser;

ALTER USER ncsUser DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CONNECT, RESOURCE, CREATE VIEW TO ncsUser;



CREATE TABLE MEMBER(

MEMBER_ID VARCHAR2(30) PRIMARY KEY,

MEMBER_PWD VARCHAR2(100) NOT NULL,

MEMBER_NM VARCHAR2(15) NOT NULL,

MEMBER_ENROLL_DT DATE DEFAULT SYSDATE

);

INSERT INTO MEMBER VALUES('user01', 'pass01', '홍길동', DEFAULT);
commit;