-- 아이디 중복 검사
SELECT COUNT(*) FROM MEMBER
WHERE MEMBER_ID = 'USER01'
AND SECESSION_FL = 'N'; -- 탈퇴를 안 한 계정

SELECT * FROM MEMBER;

-- 로그인

UPDATE MEMBER
SET SECESSION_FL = 'Y'
WHERE MEMBER NO = ? AND MEMBER_PW = ?;

SELECT MEMBER_NO, MEMBER_ID, MEMBER_GENDER, ENROLL_DATE FROM MEMBER
WHERE MEMBER_ID = 'gudtjr1355'
AND MEMBER_PW = 'dh'
AND SECESSION_FL = 'N';

SELECT MEMBER_NO, MEMBER_ID, MEMBER_GENDER, ENROLL_DATE 
	FROM MEMBER WHERE MEMBER_ID = ? AND MEMBER_PW = ? AND SECESSION_FL = 'N';
    
    DROP TABLE PRODUCT;
    
   SELECT MEMBER_NO,MEMBER_ID,MEMBER_NM,MEMBER_GENDER,ENROLL_DATE
   FROM MEMBER
   WHERE MEMBER_ID = ?
   AND MEMBER_PW = ?
   AND SECESSION_FL = 'N'    ;
    
   SELECT MEMBER_NO, MEMBER_, MEMBER_GENDER, ENROLL_DATE 
	FROM MEMBER WHERE MEMBER_ID = ? AND MEMBER_PW = ? AND SECESSION_FL = 'N' ;
    
UPDATE MEMBER
    
-- DB에서 회원 정보 모두 조회 (아이디, 이름, 가입일)
-- 단, 탈퇴 회원 제외, 아이디 오름 차순 조회
SELECT MEMBER_ID, MEMBER_NM, ENROLL_DATE
FROM MEMBER
WHERE SECESSION_FL ='N' -- 탈퇴 안한 사람만 조회
ORDER BY MEMBER_ID;
    
DELETE FROM MEMBER
WHERE MEMBER_ID = 's';
 commit;   
    
UPDATE MEMBER
SET MEMBER_NM = ?, MEMBER_GENDER = ?
WHERE MEMBER_NM = ? AND MEMBER_GENDER = ?;    
    
UPDATE MEMBER
SET MEMBER_NM = '오형스톤2', MEMBER_GENDER = 'M'
WHERE MEMBER_NM = '오형스톤' AND MEMBER_GENDER = 'M' ;
commit;

DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO INCREMENT BY 1;

UPDATE MEMBER
SET MEMBER_NM;

UPDATE MEMBER
SET MEMBER_PW = ?
WHERE MEMBER_NO = ? AND MEMBER_PW = ?


CREATE TABLE PRODUCT(
PROD_ID VARCHAR2(10) NOT NULL,
PROD_NM VARCHAR2(100) NOT NULL,
REG_DT DATE NOT NULL,
REGR_NO NUMBER(10),
CONSTRAINT PRODUCT_PK PRIMARY KEY(PROD_ID)
);

CREATE TABLE PRODUCT(
PROD_ID VARCHAR2(10) NOT NULL,
PROD_NM VARCHAR2(100) NOT NULL,
REG_DT DATE NOT NULL,
REGR_NO NUMBER(10)
);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PK PRIMARY KEY(PROD_ID); -- 테이블 만들고 추가할때는 이렇게

DROP TABLE PRODUCT; -- 전체삭제
ALTER TABLE PRODUCT DROP COLUMN PROD_ID; -- 컬럼 하나 삭제
ALTER TABLE PRODUCT DROP (PROD_NM); -- 컬럼 하나 삭제 다른 방법






