--INSERT INTO REPLY VALUES(SEQ_RNO.NEXTVAL, ?, DEFAULT, DEFAULT, ?, ?)

INSERT INTO REPLY VALUES(SEQ_RNO.NEXTVAL, 'A', DEFAULT, DEFAULT, 1, 1502);

ROLLBACK;

DELETE FROM REPLY WHERE REPLY_NO = ?;
DELETE FROM REPLY WHERE REPLY_NO = 14;

commit;

		SELECT count(*) FROM MEMBER
   		WHERE MEMBER_ID = 'testid'
   		AND SECESSION_FL = 'N';