		SELECT * FROM(
    
		    SELECT ROWNUM RNUM, A.* FROM(
		        SELECT BOARD_NO, BOARD_TITLE, MEMBER_NICK, TO_CHAR(CREATE_DT, 'YYYY-MM-DD') AS CREATE_DT, 
                READ_COUNT, (SELECT IMG_RENAME FROM BOARD_IMG
                                WHERE IMG_LEVEL = 0 AND BOARD_IMG.BOARD_NO = BOARD.BOARD_NO) THUMBNAIL
		        FROM BOARD
		        JOIN MEMBER USING(MEMBER_NO)
		        WHERE BOARD_CD = 1
		        AND BOARD_ST = 'N'
		        ORDER BY BOARD_NO DESC
		    ) A 

		)

		WHERE RNUM BETWEEN 1 AND 10;
        
-- 썸네일 조회
SELECT IMG_RENAME FROM BOARD_IMG
WHERE IMG_LEVEL = 0 AND BOARD_NO = 1661;

COMMIT;

ALTER TABLE FESTIVAL_DETAIL
MODIFY(FESTIVAL_FREE_FL VARCHAR2(300));
