--INSERT INTO REPLY VALUES(SEQ_RNO.NEXTVAL, ?, DEFAULT, DEFAULT, ?, ?)

INSERT INTO REPLY VALUES(SEQ_RNO.NEXTVAL, 'A', DEFAULT, DEFAULT, 1, 1502);

ROLLBACK;

DELETE FROM REPLY WHERE REPLY_NO = ?;
DELETE FROM REPLY WHERE REPLY_NO = 14;

commit;

		SELECT count(*) FROM MEMBER
   		WHERE MEMBER_ID = 'testid'
   		AND SECESSION_FL = 'N';
        
        
--DROP TABLE "REPLY";

CREATE TABLE "REPLY" (
   "REPLY_NO"   NUMBER      NOT NULL,
   "REPLY_CT"   VARCHAR2(200)      NOT NULL,
   "REPLY_TI"   DATE      NOT NULL,
   "REPLY_MD"   DATE      NOT NULL,
    "REPLY_ST" VARCHAR(1) DEFAULT 'N' NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글번호(시퀀스)';

COMMENT ON COLUMN "REPLY"."REPLY_CT" IS '댓글내용';

COMMENT ON COLUMN "REPLY"."REPLY_TI" IS '댓글작성시간';

COMMENT ON COLUMN "REPLY"."REPLY_MD" IS '댓글수정시간';

COMMENT ON COLUMN "REPLY"."REPLY_ST" IS '댓글 삭제 여부(N,Y)';

COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '게시글번호(시퀀스)';

COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '회원번호(시퀀스)';

ALTER TABLE "REPLY"
ADD CONSTRAINT "REPLY_BOARD_NO" 
FOREIGN KEY("BOARD_NO")
REFERENCES "BOARD";

ALTER TABLE "REPLY"
ADD CONSTRAINT "REPLY_MEMBER_NO" 
FOREIGN KEY("MEMBER_NO")
REFERENCES "MEMBER";

ALTER TABLE "REPLY"
ADD CONSTRAINT "CHK_REPLY_ST"
CHECK("REPLY_ST" IN('N','Y'));

--DROP SEQUENCE SEQ_REPLY_NO;

DROP TABLE FESTIVAL_DETAIL;

CREATE TABLE "FESTIVAL_DETAIL" (
	"FESTIVAL_NO"	NUMBER		NOT NULL,
	"FESTIVAL_DETAILINFO"	VARCHAR2(500)		NOT NULL,
	"FESTIVAL_SLOGAN"	VARCHAR2(100)		NULL,
	"FESTIVAL_PHONE"	VARCHAR2(15)		NULL,
	"FESTIVAL_FREE_FL"	VARCHAR2(6)		NULL,
	"FESTIVAL_RELATEDAGENCIES"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "FESTIVAL_DETAIL"."FESTIVAL_NO" IS '축제번호';

COMMENT ON COLUMN "FESTIVAL_DETAIL"."FESTIVAL_DETAILINFO" IS '축제 상세정보';

COMMENT ON COLUMN "FESTIVAL_DETAIL"."FESTIVAL_SLOGAN" IS '축제 슬로건';

COMMENT ON COLUMN "FESTIVAL_DETAIL"."FESTIVAL_PHONE" IS '축제 전화번호';

COMMENT ON COLUMN "FESTIVAL_DETAIL"."FESTIVAL_FREE_FL" IS '축제 유/무료 여부';

COMMENT ON COLUMN "FESTIVAL_DETAIL"."FESTIVAL_RELATEDAGENCIES" IS '축제 관련 기관';

DROP SEQUENCE SEQ_FESTIVALDETAIL_NO;

CREATE SEQUENCE SEQ_FESTIVALDETAIL_NO
       INCREMENT BY 1 -- 증가값
       START WITH 1 -- 시작값
       MINVALUE 1; -- 최솟값

BEGIN
    FOR I IN 1..180 LOOP
        
       INSERT INTO FESTIVAL_DETAIL
        VALUES(SEQ_FESTIVALDETAIL_NO.NEXTVAL,
              '해당 축제 상세내용', ' 해당 축제 슬로건', '전화번호', '무료', '해당 축제 관련 기관'
       );
        
   END LOOP;
 END;




CREATE SEQUENCE SEQ_REPLY_NO
       INCREMENT BY 1 -- 증가값
       START WITH 1 -- 시작값
       MINVALUE 1; -- 최솟값
--INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, ?, sysdate, sysdate, default, ?, ?);

INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, '테스트', SYSDATE, SYSDATE, DEFAULT, 1000, 1);
COMMIT;

--ALTER TABLE REPLY DROP CONSTRAINT FK_REPLY;

UPDATE BOARD SET READ_COUNT = READ_COUNT +1 WHERE BOARD_NO = 2030;

COMMIT;

ROLLBACK;

ALTER TABLE INFO_BOARD ADD FESTIVAL_AREA VARCHAR(20) DEFAULT '-' NOT NULL;
ALTER TABLE INFO_BOARD ADD FESTIVAL_CAT VARCHAR(20) DEFAULT '-' NOT NULL;
COMMIT;

UPDATE INFO_BOARD SET
BOARD_CD ='1'
WHERE BOARD_CD ='4'
AND FESTIVAL_NO BETWEEN 1 AND 180;

select member_no from member
join assess_member on (member_no = rec_member_no)
where memberno = ? and good_member_no = ?




