DROP TABLE MEMBER;

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(200)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_NICKNAME"	VARCHAR2(50)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(20)		NOT NULL,
	"MEMBER_BIRTH"	VARCHAR2(8)		NOT NULL,
	"MEMBER_REGION"	VARCHAR2(50)		NOT NULL,
	"MEMBER_GENDER"	CHAR(3)		NOT NULL,
	"MEMBER_NT"	VARCHAR(10)	DEFAULT 'KOR'	NOT NULL,
	"MEMBER_PHONE"	VARCHAR(20)		NOT NULL,
	"ENROLL_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ADMIN_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"SECESSION_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_PROFILE"	VARCHAR2(4000)		NULL,
	"MEMBER_MESSAGE"	VARCHAR2(400)		NULL
);

		SELECT  MEMBER_NO, MEMBER_ID, MEMBER_EMAIL, MEMBER_NICKNAME, MEMBER_NAME, MEMBER_BIRTH, MEMBER_REGION, MEMBER_GENDER, MEMBER_NT,
        MEMBER_PHONE, ENROLL_DT, ADMIN_FL, MEMBER_PROFILE, MEMBER_MESSAGE FROM MEMBER
		WHERE MEMBER_ID = ? AND MEMBER_PW = ? AND SECESSION_FL = 'N'

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(시퀀스)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '회원 생년월일';

COMMENT ON COLUMN "MEMBER"."MEMBER_REGION" IS '회원 활동 지역';

COMMENT ON COLUMN "MEMBER"."MEMBER_GENDER" IS '회원 성별';

COMMENT ON COLUMN "MEMBER"."MEMBER_NT" IS '내국인/외국인';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '휴대폰 번호';

COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '가입일';

COMMENT ON COLUMN "MEMBER"."ADMIN_FL" IS '관리자 권한';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴여부';

COMMENT ON COLUMN "MEMBER"."MEMBER_PROFILE" IS '회원 이미지파일';

COMMENT ON COLUMN "MEMBER"."MEMBER_MESSAGE" IS '프로필 메시지';

DROP SEQUENCE SEQ_MEMBER_NO;

CREATE SEQUENCE SEQ_MEMBER_NO INCREMENT BY 1;

INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'testid', 'testpw', 'testemail', 'testnick', 'testname', TO_DATE('19971030', 'YYYYMMDD'), '서울', '남', DEFAULT, '01033339999', DEFAULT, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, ?, ?, ?, ?, ?, TO_DATE(?, 'YYYYMMDD'), ?, ?, ?, ?, DEFAULT, DEFAULT, DEFAULT, NULL, NULL);
rollback;
commit;


SEQ_MEMBER_NO.NEXTVAL, 'testid', 'testpw', 'testemail', 'testnick', 'testname', 
TO_DATE('19971030', 'YYYYMMDD'), '서울', '남', DEFAULT, '01033339999', DEFAULT, DEFAULT, DEFAULT, NULL, NULL



