-- sys 관리자 계정
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER semi_festival IDENTIFIED BY festival1234;

ALTER USER semi_festival DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CONNECT, RESOURCE, CREATE VIEW TO semi_festival;

-- festival 계정
--DROP TABLE MEMBER;

CREATE TABLE MEMBER (

    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(30) NOT NULL UNIQUE,
    MEMBER_PW VARCHAR2(200) NOT NULL,
    MEMBER_EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    MEMBER_NICKNAME VARCHAR2(30) NOT NULL UNIQUE,
    MEMBER_NAME VARCHAR2(30) NOT NULL,
    MEMBER_BIRTH VARCHAR2(30) NOT NULL,
    MEMBER_REGION VARCHAR2(200) NOT NULL,
    MEMBER_TC VARCHAR2(20) NOT NULL,
    MEMBER_PHONE VARCHAR2(20) NOT NULL,
    MEMBER_GENDER VARCHAR2(6) NOT NULL,
    MEMBER_NATIONALITY VARCHAR2(12) NOT NULL,
    MEMBER_PROFILEIMAGE VARCHAR2(4000),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    SECESSION_FL CHAR(1) DEFAULT 'N'

);

CREATE SEQUENCE SEQ_MEMBER_NO
INCREMENT BY 1;

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디(중복X)';
COMMENT ON COLUMN MEMBER.MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '회원 이메일(중복X)';
COMMENT ON COLUMN MEMBER.MEMBER_NICKNAME IS '회원 닉네임(중복X)';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.MEMBER_BIRTH IS '회원 생년월일( - 미포함)';
COMMENT ON COLUMN MEMBER.MEMBER_REGION IS '회원 주 활동지역';
COMMENT ON COLUMN MEMBER.MEMBER_TC IS '회원 통신사';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '전화번호( - 미포함)';
COMMENT ON COLUMN MEMBER.MEMBER_GENDER IS '회원 성별';
COMMENT ON COLUMN MEMBER.MEMBER_NATIONALITY IS '회원 국적';
COMMENT ON COLUMN MEMBER.MEMBER_PROFILEIMAGE IS '회원 프로필 이미지';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN MEMBER.SECESSION_FL IS '탈퇴여부(Y:탈퇴, N:미탈퇴)';

-- 회원 번호 시퀀스

INSERT INTO MEMBER VALUES
(SEQ_MEMBER_NO.NEXTVAL, 'testid', 'testpw', 'testemail', 'testnick', 
'testname', '200020202', '서울', 'skt', '01033339999', '남자', '내국인', 'img', default, default);