SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_GRADE;
--1
SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS 계열 FROM TB_DEPARTMENT;

--2
SELECT DEPARTMENT_NAME ||'의 정원은 ' || CAPACITY || '명 입니다.' AS "학과별 정원" FROM TB_DEPARTMENT;

--3
SELECT STUDENT_NAME FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과' AND SUBSTR(STUDENT_SSN, 8, 1) = '2' AND ABSENCE_YN = 'Y'; 

--4
SELECT STUDENT_NAME FROM TB_STUDENT
WHERE STUDENT_NAME IN ('홍경희', '최경희', '정경훈', '정경환', '이경환');

--5
SELECT DEPARTMENT_NAME, CATEGORY FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6
SELECT PROFESSOR_NAME FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7
SELECT STUDENT_NAME FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8
SELECT CLASS_NO FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9
SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT;

--10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN FROM TB_STUDENT
WHERE SUBSTR(ENTRANCE_DATE,1, 4) = '2002' AND STUDENT_ADDRESS LIKE '%전주%' AND (ABSENCE_YN = 'N');
