--1 
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

--3
SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000 AND (STUDENT_ADDRESS LIKE '강원도%' OR STUDENT_ADDRESS LIKE '경기도%')
ORDER BY 1;

--4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = 005
ORDER BY PROFESSOR_SSN;

--5
SELECT STUDENT_NO, TO_CHAR(POINT, '9.99') POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100' AND TERM_NO = 200402
ORDER BY 2 DESC, 1 ASC;

--6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;

--7
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

--8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO); 
--바로 JOIN TB_PROFESSOR USING(DEPARTMENT_NO) 하면 
--DEPARTMENT_NO가 001이 2명이라 이상하게뜸 임희도랑 김선진 PROFESSOR_NO이 다름

SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS A,  TB_CLASS_PROFESSOR B, TB_PROFESSOR C
WHERE A.CLASS_NO = B.CLASS_NO
AND B.PROFESSOR_NO = C.PROFESSOR_NO;

-- 같은 컬럼 값을 가지는 DEPARTMENT_NO가 많이 존재하는 경우
-- TB_CLASS의 DEPARTMENT_NO와
-- TB_PROFESSOR의 DEPARTMENT_NO 컬럼 값들이
-- 서로 연결되기 위한 모든 경우의 수를 만들어낸다.


--9
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS A
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO) 
WHERE A.DEPARTMENT_NO BETWEEN '001' AND '021';

--ORACLE
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS A, TB_CLASS_PROFESSOR B, TB_PROFESSOR C
WHERE A.CLASS_NO = B.CLASS_NO
AND B.PROFESSOR_NO = C.PROFESSOR_NO
AND A.DEPARTMENT_NO BETWEEN '001' AND '021';

SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS A, TB_CLASS_PROFESSOR B, TB_PROFESSOR C, TB_DEPARTMENT D
WHERE A.CLASS_NO = B.CLASS_NO
AND B.PROFESSOR_NO = C.PROFESSOR_NO
AND C.DEPARTMENT_NO = D.DEPARTMENT_NO
AND CATEGORY = '인문사회';

--10
SELECT STUDENT_NO "학번", STUDENT_NAME "학생 이름", ROUND(AVG(POINT), 1) "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = 059
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY 1;

SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_GRADE;

--11
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

SELECT * FROM TB_STUDENT
WHERE STUDENT_NAME = '손건영';
--A313047	008	손건영	840718-1164847	인천광역시 남동구 논현동 풍림아파트 107-1205	2003-03-01 00:00:00	N	P034
--P034	박태환	600704-1138184	경기 안양시 만안구 석수1동373-3백조(A)202동506	026

--12 
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE CLASS_NAME = '인간관계론' AND TERM_NO LIKE '2007%';

--13
SELECT CLASS_NAME, DEPARTMENT_NAME, PROFESSOR_NO FROM TB_CLASS 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO) 
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL;

--14
SELECT STUDENT_NAME "학생이름", NVL(PROFESSOR_NAME, '지도교수 미지정') "지도교수"
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY ENTRANCE_DATE;

-- 15 
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", ROUND(AVG(POINT),8) 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY STUDENT_NO;

-- 16 
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT), 8) "AVG(POINT)"
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND CLASS_TYPE = '전공선택'
GROUP BY CLASS_NO, CLASS_NAME;

-- 17
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = (SELECT DEPARTMENT_NAME FROM TB_STUDENT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO) WHERE STUDENT_NAME = '최경희');

-- 18 
-- 인라인뷰
SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT
        JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
        JOIN TB_GRADE USING (STUDENT_NO)
        WHERE DEPARTMENT_NAME = '국어국문학과'
        GROUP BY STUDENT_NO, STUDENT_NAME
        ORDER BY AVG(POINT) DESC)
        WHERE ROWNUM = 1;
        
SELECT STUDENT_NO, STUDENT_NAME
FROM 
(SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT) 평점
        FROM TB_GRADE 
        JOIN TB_STUDENT USING(STUDENT_NO)
        WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '국어국문학과')
        GROUP BY STUDENT_NO, STUDENT_NAME
        ORDER BY 평점 DESC)
        WHERE ROWNUM = 1;

 SELECT ROWNUM, STUDENT_NO, STUDENT_NAME FROM TB_STUDENT 
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
    JOIN TB_GRADE USING(STUDENT_NO) 
    WHERE ROWNUM = 1 AND DEPARTMENT_NAME = '국어국문학과' 
    GROUP BY ROWNUM, STUDENT_NO, STUDENT_NAME 
    ORDER BY AVG(POINT) DESC; -- ORDER BY 전에 ROWNUM = 1이 되어버림

-- 19
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1) "전공평점"
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '환경조경학과')
AND CLASS_TYPE = '전공선택'
GROUP BY DEPARTMENT_NAME
ORDER BY 1;


SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_GRADE;
