/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-07-27 08:34:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class festivalInformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1688615093168L));
    _jspx_dependants.put("jar:file:/C:/workspace/5_Server/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/semiworkspace/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>축제정보</title>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/51fc103959.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/festivalInformation.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/footer.css\">\r\n");
      out.write("   \r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Hi+Melody&family=Moirai+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css\" />\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <main>\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"swiper mySwiper\">\r\n");
      out.write("            <div class=\"swiper-wrapper\">\r\n");
      out.write("              <div class=\"swiper-slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con2.jpg\"></div>\r\n");
      out.write("              <div class=\"swiper-slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con3.jpg\"></div>\r\n");
      out.write("              <div class=\"swiper-slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con1.jpg\"></div>\r\n");
      out.write("              <div class=\"swiper-slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con2.jpg\"></div>\r\n");
      out.write("              <div class=\"swiper-slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con3.jpg\"></div>\r\n");
      out.write("              <div class=\"swiper-slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con1.jpg\"></div>\r\n");
      out.write("              <div class=\"swiper-slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con3.jpg\"></div>\r\n");
      out.write("              <div class=\"swiper-slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con2.jpg\"></div>\r\n");
      out.write("              <div class=\"swiper-slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con1.jpg\"></div>\r\n");
      out.write("              <div class=\"swiper-slide\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con2.jpg\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"swiper-pagination\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 검색게시판 타이틀 -->\r\n");
      out.write("    <section class=\"title-box\"> 전국 축제검색 게시판</section>\r\n");
      out.write("\r\n");
      out.write("    <!-- 컨텐츠 -->\r\n");
      out.write("    <section class=\"content\">\r\n");
      out.write("        <form action=\"\">\r\n");
      out.write("        <div class=\"selectBoxList\">\r\n");
      out.write("            <!-- selectBox1 -->\r\n");
      out.write("            <div class=\"box\">\r\n");
      out.write("                <div class=\"selectBox \">\r\n");
      out.write("                    <div class=\"label\">\r\n");
      out.write("                        <i class=\"fa-regular fa-calendar-check\"></i>\r\n");
      out.write("                        <span> 시기별 :</span>\r\n");
      out.write("                        <span id=\"sp1\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"optionList\">\r\n");
      out.write("                        <li class=\"optionItem\">2023년</li>\r\n");
      out.write("                        <li class=\"optionItem\">2022년</li>\r\n");
      out.write("                        <li class=\"optionItem\">2021년</li>\r\n");
      out.write("                        <li class=\"optionItem\">2020년</li>\r\n");
      out.write("                        <li class=\"optionItem\">2023년</li>\r\n");
      out.write("                        <li class=\"optionItem\">2022년</li>\r\n");
      out.write("                        <li class=\"optionItem\">2021년</li>\r\n");
      out.write("                        <li class=\"optionItem\">2020년</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- selectBox2 -->\r\n");
      out.write("            <div class=\"box\">\r\n");
      out.write("                <div class=\"selectBox\">\r\n");
      out.write("                    <div class=\"label\">\r\n");
      out.write("                        <i class=\"fa-solid fa-map-location-dot\"></i>\r\n");
      out.write("                        <span> 지역별 :</span>\r\n");
      out.write("                        <span id=\"sp2\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"optionList\">\r\n");
      out.write("                        <li class=\"optionItem\">서울</li>\r\n");
      out.write("                        <li class=\"optionItem\">경기도</li>\r\n");
      out.write("                        <li class=\"optionItem\">부산</li>\r\n");
      out.write("                        <li class=\"optionItem\">시발</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- selectBox3 -->\r\n");
      out.write("            <div class=\"box\">\r\n");
      out.write("                <div class=\"selectBox\">\r\n");
      out.write("                    <div class=\"label\">\r\n");
      out.write("                        <i class=\"fa-solid fa-tag\"></i>\r\n");
      out.write("                        <span> 카테고리 :</span>\r\n");
      out.write("                        <span id=\"sp3\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"optionList\">\r\n");
      out.write("                        <li class=\"optionItem\">카</li>\r\n");
      out.write("                        <li class=\"optionItem\">테</li>\r\n");
      out.write("                        <li class=\"optionItem\">고</li>\r\n");
      out.write("                        <li class=\"optionItem\">리</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"reset\" id=\"reset\"><i class=\"fa-solid fa-repeat\"></i></button>\r\n");
      out.write("            <button type=\"submit\" id=\"info-search\">검색</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"content2\">\r\n");
      out.write("        <div id=\"span-box\">\r\n");
      out.write("        <span class=\"festival-date\">축제일순</span><span class=\"popularity\">인기순</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"grid-container\">\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"item-image\"><a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/con1.jpg\" alt=\"\"></a></div>\r\n");
      out.write("                <div class=\"item-text\">\r\n");
      out.write("                    \r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                    <div class=\"item-title\"><h1>대한민국축제</h1><span>2023.xx.xx</span></div>\r\n");
      out.write("                    <span class=\"item-content\">dddddddddddddddddddddddddd</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"item-image\">이미지</div>\r\n");
      out.write("                <div class=\"item-text\">텍스트</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"item-image\">이미지</div>\r\n");
      out.write("                <div class=\"item-text\">텍스트</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"item-image\">이미지</div>\r\n");
      out.write("                <div class=\"item-text\">텍스트</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"item-image\">이미지</div>\r\n");
      out.write("                <div class=\"item-text\">텍스트</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"item-image\">이미지</div>\r\n");
      out.write("                <div class=\"item-text\">텍스트</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"item-image\">이미지</div>\r\n");
      out.write("                <div class=\"item-text\">텍스트</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"item-image\">이미지</div>\r\n");
      out.write("                <div class=\"item-text\">텍스트</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("                <div class=\"item-image\">이미지</div>\r\n");
      out.write("                <div class=\"item-text\">\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"button-box\">\r\n");
      out.write("        <button><</button>\r\n");
      out.write("        <button>1</button>\r\n");
      out.write("        <button>2</button>\r\n");
      out.write("        <button>3</button>\r\n");
      out.write("        <button>4</button>\r\n");
      out.write("        <button>5</button>\r\n");
      out.write("        <button>></button>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/festival-Information.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
